---
version: 2.1

setup: true

orbs:
  orb-tools: circleci/orb-tools@12.0.4
  shellcheck: circleci/shellcheck@3.2.0

globals:
  - &context orb-publishing
  - &orb-name twdps/executor-tools

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /^[0-9]+\.[0-9]+\.[0-9]+$/

workflows:

  development build and test:
    jobs:

      - orb-tools/lint:
          filters: *on-push-main

      - orb-tools/review:
          max_command_length: 100
          exclude: RC006,RC010,RC007,RC003
          filters: *on-push-main

      - shellcheck/check:
          filters: *on-push-main
