# src/commands/build.yaml

description: Build executor Docker image

parameters:

  dockerfile:
    description: Name of dockerfile
    type: string
    default: Dockerfile

  docker-build-path:
    description: Path to the directory containing your Dockerfile and build context
    type: string
    default: .

  registry:
    description: Name of registry
    type: string
    default: "docker.io"

  image:
    description: Name of image
    type: string

  tag:
    description: Value for tag
    type: string
    default: $CIRCLE_SHA1

  extra-build-args:
    description: >
      Extra flags to pass to docker build. For examples, see
      https://docs.docker.com/engine/reference/commandline/build
    type: string
    default: ""

steps:
  - run:
      name: Build executor Docker image
      command: |
        echo "Dockerfile: << parameters.dockerfile >>"
        echo "image: << parameters.registry >>/<< parameters.image >>:<< parameters.tag >>"
        docker build -f << parameters.dockerfile >> \
                     -t << parameters.registry >>/<< parameters.image >>:<< parameters.tag >> \
                     <<parameters.extra-build-args>> \
                     << parameters.docker-build-path >>
