# src/commands/configure-machine.yaml

description: |
  Install additional tools on standard circleci ubuntu machine executor.
  Note. conftest installs a specific version that can be overridden.

parameters:

  conftest-version:
    description: specify conftest version
    type: string

  opw-version:
    description: specify opw version
    type: string

steps:
  - run:
      name: install secrethub
      command: |
        curl -sLJO https://deb.secrethub.io/amd64
        sudo dpkg -i secrethub-cli-amd64.deb
        rm secrethub-cli-amd64.deb
  - run:
      name: install 1password
      command: |
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" | sudo tee /etc/apt/sources.list.d/1password.list
        sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/
        curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
        sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
        curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
        sudo apt update && sudo apt install 1password-cli
        op --version
  - run:
      name: install opw - 1password writer
      command: |
        curl -SLO https://github.com/ThoughtWorks-DPS/opw/releases/download/<< parameters.opw-version >>/opw_<< parameters.opw-version >>_Linux_x86_64.tar.gz
        tar -xzf opw_<< parameters.opw-version >>_Linux_x86_64.tar.gz
        sudo mv opw /usr/local/bin/opw
  - run:
      name: install conftest
      command: |
        wget https://github.com/open-policy-agent/conftest/releases/download/v<< parameters.conftest-version >>/conftest_<< parameters.conftest-version >>_Linux_x86_64.tar.gz
        tar xzf conftest_<< parameters.conftest-version >>_Linux_x86_64.tar.gz
        sudo mv conftest /usr/local/bin
  - run:
      name: install snyk
      command: npm install -g snyk
  - run:
      name: install bats
      command: npm install -g bats
  - run:
      name: install inspec
      command: |
        curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
        sudo mkdir -p /etc/chef/accepted_licenses
        sudo bash -c "echo '---' > /etc/chef/accepted_licenses/inspec"
        sudo bash -c "echo 'id: inspec' >> /etc/chef/accepted_licenses/inspec"
        sudo bash -c "echo 'name: Chef InSpec' >> /etc/chef/accepted_licenses/inspec"
        sudo bash -c "echo 'accepting_product: inspec' >> /etc/chef/accepted_licenses/inspec"
        sudo bash -c "echo 'file_format: 1' >> /etc/chef/accepted_licenses/inspec"
